name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      run: |
        apt install clang-format
        echo $(pwd)
        ./lint.sh ${{ github.workspace }}
